### ISSUE TITLE
Bad Timestamps for `coauth-MAG-History`

### ISSUE THREAD

**Issue by tlarock** [xgi-org/xgi-data#29]
The format of yearly timestamps for the `coauth-MAG-History` dataset appears to be incorrect. For example:
```
import xgi
hg = xgi.load_xgi_data("coauth-MAG-History")
for e, edat in hg.edges.items():
    print(e, " ", edat)
    break
```
Yields:
> 0   {'timestamp': '0001-01-01T00:00:02.004000'}

Presumably, this edge occured in 2004, but the year has been overformatted into a timestamp such that the information is spread across seconds/miliseconds, rather than in the year slot.

I checked and the same issue does not occur with the `coauth-MAG-Geology` data, so it might just be this one dataset.

**Comment by nwlandry** [comment]
@tlarock great catch! I won't have the time for a few weeks to get to this, so feel free to go through the process of updating the record on Zenodo if you would like. It looks like if you copy the line from `coauth_MAG_geology` for the timestamp, it should fix the issue.
